name: Build

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:
  
env:
  APP_NAME: "com-master"
  BUILD_TYPE: "Release"

jobs:
  build-deb:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - platform: amd64
            image: linuxdeepin/deepin:crimson
          - platform: arm64
            image: linuxdeepin/deepin:crimson-arm64
          - platform: loong64
            image: linuxdeepin/deepin:crimson-loong64
          - platform: riscv64
            image: linuxdeepin/deepin:crimson-riscv64
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
      with:
        platforms: ${{ matrix.platform }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - uses: actions/checkout@v7

    - name: Build ${{ matrix.platform }} package
      run: |
        docker run --rm --platform linux/${{ matrix.platform }} -v ${{ github.workspace }}:/workspace \
          ${{ matrix.image }} \
          bash -c "
          cd /workspace &&
          apt update &&
          apt install -y build-essential devscripts dh-make equivs &&
          mk-build-deps -i -t 'apt-get -y' './debian/control' &&
          debuild -us -uc &&
          cp ../*.deb ./
          "

    - name: Move deb to deb_package
      run: |
        if ls ./*dbgsym*.deb 1> /dev/null 2>&1; then
          rm ./*dbgsym*.deb
        fi

        if ls ./*build-deps*.deb 1> /dev/null 2>&1; then
          rm ./*build-deps*.deb
        fi
        
        mkdir deb_package
        cp ./*.deb deb_package

    - name: 'Upload artifact: deb'
      uses: actions/upload-artifact@v7
      with:
          name: ${{ env.APP_NAME }}_linux_deb_${{ matrix.platform }}
          path: deb_package/*.deb
      
  build-windows:
    runs-on: ${{ matrix.config.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            msystem: ucrt64
            platform_tag: win_x64                 
          - os: windows-11-arm
            msystem: clangarm64
            platform_tag: win_arm64
    defaults:
      run:
        shell: msys2 {0}
    steps:  
    - name: Disable autocrlf in Git
      shell: pwsh
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Set up MSYS2 environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.config.msystem }}
        cache: true
        update: true
        install: bison flex dos2unix curl zip p7zip
        pacboy: cmake:p gcc:p qt6-base:p qt6-tools:p qt6-svg:p qt6-serialport:p make:p ninja:p libssh:p libpcap:p

    - name: Build project with CMake
      run: |
        cmake.exe -B build/ -G 'Ninja' \
                  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                  -DCMAKE_INSTALL_PREFIX=build/${{ env.APP_NAME }}
        cmake.exe --build build/ --parallel --config ${{env.BUILD_TYPE}}

    - name: Get PROJECT_VERSION from VERSION file
      shell: pwsh
      run: |
        $version = Get-Content VERSION -First 1
        echo "APP_VERSION=$version" >> $env:GITHUB_ENV
        echo "Version: $version"

    - name: Make install
      run: |
        cmake --build build/ --target install
        strip build/${{ env.APP_NAME }}/bin/*.exe 

    - name: Deploy Qt6 dependencies
      run: |
        deploy_tool="windeployqt.exe"
        bin_dir="build/${{ env.APP_NAME }}/bin"
        options="--svg --no-translations --no-system-d3d-compiler"

        executables=(
          "${{ env.APP_NAME }}.exe"
        )

        for exe in "${executables[@]}"; do
          $deploy_tool "$bin_dir/$exe" $options
        done
          
    - name: Copy non-Qt DLLs to bin directory
      run: |
        shopt -s extglob
        FILES=$(ldd build/${{ env.APP_NAME }}/bin/${{ env.APP_NAME }}.exe | awk '($3 ~ /\/${{ matrix.config.msystem }}\/bin\//) {print $3}')
        for file in $FILES; do
          if [[ $(basename "$file") != Qt6* ]]; then
            echo "Copying: $file"
            cp -r "$file" build/${{ env.APP_NAME }}/bin
          fi
        done
            
    - name: Create zip archive for release
      run: |
        mkdir -p build/${{ env.APP_NAME }}
        cd build/${{ env.APP_NAME }}
        zip -r ../../${{ env.APP_NAME }}_${{ env.APP_VERSION }}_${{ matrix.config.platform_tag }}.zip ./bin ./share ./lib
        cd ../..

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.APP_NAME }}_${{ env.APP_VERSION }}_${{ matrix.config.platform_tag }}
        path: ${{ env.APP_NAME }}_${{ env.APP_VERSION }}_${{ matrix.config.platform_tag }}.zip

  create-release:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: [build-deb, build-windows]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Download build artifacts
      uses: actions/download-artifact@v8
      with:
        path: ~/artifacts
        merge-multiple: true

    - name: Calculate SHA-256 checksums
      run: |
        cd ~/artifacts
        > hashes.sha256
        for file in $(find . -type f \( -name "*.deb" -o -name "*-win-arm64.zip" -o -name "*-win-x64.zip" \)); do
          filename=$(basename "$file")
          sha256sum "$file" | awk -v fname="$filename" '{print $1 " *" fname}' >> hashes.sha256
        done
        cd ..
        tree ~/artifacts

    - name: Setup Release Information
      run: |
        if [ "${{github.ref_type}}" == "tag" ]; then
          echo "PRERELEASE=" >> $GITHUB_ENV
          echo "RELEASE_NAME=${{ env.APP_NAME }} ${{ github.ref_name }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "RELEASE_NOTES=--generate-notes" >> $GITHUB_ENV
        else
          echo "PRERELEASE=-p" >> $GITHUB_ENV
          echo "RELEASE_NAME=Continuous Build" >> $GITHUB_ENV
          echo "TAG_NAME=continuous_build" >> $GITHUB_ENV
          echo "RELEASE_NOTES=--notes \"Automated release for commit ${{ github.sha }}\"" >> $GITHUB_ENV
        fi
          
    - name: Create GitHub Release
      continue-on-error: false
      run: |
        # Find existing artifact files
        zip_files=$(find ~/artifacts -name "*win*.zip"  -print0 | xargs -0 echo)
        deb_files=$(find ~/artifacts -name "*.deb" -print0 | xargs -0 echo)

        # Check existing release and delete if it's exist
        if gh release view ${{ env.TAG_NAME }} --repo $GITHUB_REPOSITORY &> /dev/null; then
          if [ "${{ env.TAG_NAME }}" == "continuous_build" ]; then
            gh release delete ${{ env.TAG_NAME }} --repo $GITHUB_REPOSITORY --cleanup-tag  --yes
          else
            gh release delete ${{ env.TAG_NAME }} --repo $GITHUB_REPOSITORY
          fi
          echo "${{ env.TAG_NAME }} deleted!"
        fi
        
        if [ -n "$zip_files" ] && [ -n "$deb_files" ]; then
          gh release create ${{ env.TAG_NAME }} \
                            $zip_files \
                            $deb_files \
                            ${{ env.PRERELEASE }} \
                            --repo $GITHUB_REPOSITORY \
                            --title "${{ env.RELEASE_NAME }}" \
                            ${{ env.RELEASE_NOTES }}

            echo "${{ env.TAG_NAME }} release created!"
        else
          echo "No artifacts to upload."
          exit 1
        fi
        
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
